#!/usr/bin/env bash
# Run 100 Test262 batches (next 100 not yet in CONFORMANCE). Doc + commit each.
set -e
REPO=/home/gamarino/Documentos/proyectos/protoJS
CONFIG="$REPO/tests/test262/config/test262_paths.json"
RUNNER="$REPO/tests/test262/runner/test262_runner.js"
ADD_ROW="$REPO/tests/test262/runner/add_conformance_row.js"
export PROTOJS=$REPO/build/protojs
export TEST262_ROOT=/home/gamarino/Documentos/proyectos/test262
cd "$REPO"

patterns=(
  "built-ins/Temporal/ZonedDateTime/prototype/inLeapYear"
  "built-ins/Temporal/ZonedDateTime/prototype/microsecond"
  "built-ins/Temporal/ZonedDateTime/prototype/millisecond"
  "built-ins/Temporal/ZonedDateTime/prototype/month"
  "built-ins/Temporal/ZonedDateTime/prototype/monthCode"
  "built-ins/Temporal/ZonedDateTime/prototype/monthsInYear"
  "built-ins/Temporal/ZonedDateTime/prototype/nanosecond"
  "built-ins/Temporal/ZonedDateTime/prototype/offset"
  "built-ins/Temporal/ZonedDateTime/prototype/offsetNanoseconds"
  "built-ins/Temporal/ZonedDateTime/prototype/round"
  "built-ins/Temporal/ZonedDateTime/prototype/second"
  "built-ins/Temporal/ZonedDateTime/prototype/since"
  "built-ins/Temporal/ZonedDateTime/prototype/startOfDay"
  "built-ins/Temporal/ZonedDateTime/prototype/subtract"
  "built-ins/Temporal/ZonedDateTime/prototype/toJSON"
  "built-ins/Temporal/ZonedDateTime/prototype/toLocaleString"
  "built-ins/Temporal/ZonedDateTime/prototype/toPlainDate"
  "built-ins/Temporal/ZonedDateTime/prototype/toPlainDateTime"
  "built-ins/Temporal/ZonedDateTime/prototype/toPlainTime"
  "built-ins/Temporal/ZonedDateTime/prototype/toStringTag"
  "built-ins/Temporal/ZonedDateTime/prototype/until"
  "built-ins/Temporal/ZonedDateTime/prototype/valueOf"
  "built-ins/Temporal/ZonedDateTime/prototype/weekOfYear"
  "built-ins/Temporal/ZonedDateTime/prototype/with"
  "built-ins/Temporal/ZonedDateTime/prototype/withCalendar"
  "built-ins/Temporal/ZonedDateTime/prototype/withPlainTime"
  "built-ins/Temporal/ZonedDateTime/prototype/withTimeZone"
  "built-ins/Temporal/ZonedDateTime/prototype/year"
  "built-ins/Temporal/ZonedDateTime/prototype/yearOfWeek"
  "built-ins/ThrowTypeError"
  "built-ins/TypedArray"
  "built-ins/TypedArrayConstructors"
  "built-ins/TypedArrayConstructors/BigInt64Array"
  "built-ins/TypedArrayConstructors/BigInt64Array/prototype"
  "built-ins/TypedArrayConstructors/BigUint64Array"
  "built-ins/TypedArrayConstructors/BigUint64Array/prototype"
  "built-ins/TypedArrayConstructors/ctors"
  "built-ins/TypedArrayConstructors/ctors-bigint"
  "built-ins/TypedArrayConstructors/ctors-bigint/buffer-arg"
  "built-ins/TypedArrayConstructors/ctors-bigint/length-arg"
  "built-ins/TypedArrayConstructors/ctors-bigint/no-args"
  "built-ins/TypedArrayConstructors/ctors-bigint/object-arg"
  "built-ins/TypedArrayConstructors/ctors-bigint/typedarray-arg"
  "built-ins/TypedArrayConstructors/ctors/buffer-arg"
  "built-ins/TypedArrayConstructors/ctors/length-arg"
  "built-ins/TypedArrayConstructors/ctors/no-args"
  "built-ins/TypedArrayConstructors/ctors/object-arg"
  "built-ins/TypedArrayConstructors/ctors/typedarray-arg"
  "built-ins/TypedArrayConstructors/Float32Array/prototype"
  "built-ins/TypedArrayConstructors/Float64Array/prototype"
  "built-ins/TypedArrayConstructors/from/BigInt"
  "built-ins/TypedArrayConstructors/Int16Array/prototype"
  "built-ins/TypedArrayConstructors/Int32Array/prototype"
  "built-ins/TypedArrayConstructors/Int8Array/prototype"
  "built-ins/TypedArrayConstructors/internals"
  "built-ins/TypedArrayConstructors/internals/DefineOwnProperty"
  "built-ins/TypedArrayConstructors/internals/DefineOwnProperty/BigInt"
  "built-ins/TypedArrayConstructors/internals/Delete"
  "built-ins/TypedArrayConstructors/internals/Delete/BigInt"
  "built-ins/TypedArrayConstructors/internals/Get"
  "built-ins/TypedArrayConstructors/internals/Get/BigInt"
  "built-ins/TypedArrayConstructors/internals/GetOwnProperty"
  "built-ins/TypedArrayConstructors/internals/GetOwnProperty/BigInt"
  "built-ins/TypedArrayConstructors/internals/HasProperty"
  "built-ins/TypedArrayConstructors/internals/HasProperty/BigInt"
  "built-ins/TypedArrayConstructors/internals/OwnPropertyKeys"
  "built-ins/TypedArrayConstructors/internals/OwnPropertyKeys/BigInt"
  "built-ins/TypedArrayConstructors/internals/Set"
  "built-ins/TypedArrayConstructors/internals/Set/BigInt"
  "built-ins/TypedArrayConstructors/of/BigInt"
  "built-ins/TypedArrayConstructors/prototype"
  "built-ins/TypedArrayConstructors/prototype/buffer"
  "built-ins/TypedArrayConstructors/prototype/byteLength"
  "built-ins/TypedArrayConstructors/prototype/byteOffset"
  "built-ins/TypedArrayConstructors/prototype/copyWithin"
  "built-ins/TypedArrayConstructors/prototype/entries"
  "built-ins/TypedArrayConstructors/prototype/every"
  "built-ins/TypedArrayConstructors/prototype/fill"
  "built-ins/TypedArrayConstructors/prototype/filter"
  "built-ins/TypedArrayConstructors/prototype/find"
  "built-ins/TypedArrayConstructors/prototype/findIndex"
  "built-ins/TypedArrayConstructors/prototype/forEach"
  "built-ins/TypedArrayConstructors/prototype/indexOf"
  "built-ins/TypedArrayConstructors/prototype/join"
  "built-ins/TypedArrayConstructors/prototype/keys"
  "built-ins/TypedArrayConstructors/prototype/lastIndexOf"
  "built-ins/TypedArrayConstructors/prototype/length"
  "built-ins/TypedArrayConstructors/prototype/map"
  "built-ins/TypedArrayConstructors/prototype/reduce"
  "built-ins/TypedArrayConstructors/prototype/reduceRight"
  "built-ins/TypedArrayConstructors/prototype/reverse"
  "built-ins/TypedArrayConstructors/prototype/set"
  "built-ins/TypedArrayConstructors/prototype/slice"
  "built-ins/TypedArrayConstructors/prototype/some"
  "built-ins/TypedArrayConstructors/prototype/sort"
  "built-ins/TypedArrayConstructors/prototype/subarray"
  "built-ins/TypedArrayConstructors/prototype/Symbol.toStringTag"
  "built-ins/TypedArrayConstructors/prototype/toLocaleString"
  "built-ins/TypedArrayConstructors/prototype/toString"
  "built-ins/TypedArrayConstructors/prototype/values"
)

for p in "${patterns[@]}"; do
  node -e "
  const fs=require('fs');
  const cfg=JSON.parse(fs.readFileSync('$CONFIG','utf8'));
  cfg.patterns=['$p'];
  fs.writeFileSync('$CONFIG', JSON.stringify(cfg, null, 2));
  "
  out=$(node "$RUNNER" 2>&1) || true
  snap=$(echo "$out" | grep -o 'tests/test262/reports/snapshot-[^ ]*\.json' | tail -1)
  if [ -z "$snap" ] || [ ! -f "$REPO/$snap" ]; then echo "No snapshot for $p"; exit 1; fi
  read -r total passed fs fm to <<< $(node -e "const s=require('./$snap'); console.log(s.total, s.summary.passed, s.summary.failed_syntax, s.summary.failed_semantics, s.summary.timeout)")
  node "$ADD_ROW" "$p" "$total" "$passed" "$fs" "$fm" "$to"
  git add CONFORMANCE_JS.md "$CONFIG" "$snap"
  git commit -m "docs(test262): record $p conformance"
  echo "Done: $p ($total tests)"
done
echo "All 100 batches done."
