#!/usr/bin/env bash
# Run 100 Test262 batches: for each pattern, update config, run runner, append row to CONFORMANCE_JS.md, commit.
set -e
REPO=/home/gamarino/Documentos/proyectos/protoJS
CONFIG="$REPO/tests/test262/config/test262_paths.json"
RUNNER="$REPO/tests/test262/runner/test262_runner.js"
ADD_ROW="$REPO/tests/test262/runner/add_conformance_row.js"
export PROTOJS=$REPO/build/protojs
export TEST262_ROOT=/home/gamarino/Documentos/proyectos/test262
cd "$REPO"

# 100 patterns not yet in CONFORMANCE_JS (continuation after globalThis)
patterns=(
  "built-ins/ArrayBuffer/prototype"
  "built-ins/ArrayBuffer/prototype/byteLength"
  "built-ins/ArrayBuffer/prototype/slice"
  "built-ins/Boolean/prototype"
  "built-ins/BigInt/asIntN"
  "built-ins/BigInt/asUintN"
  "built-ins/BigInt/prototype"
  "built-ins/Number/isSafeInteger"
  "built-ins/Number/MAX_VALUE"
  "built-ins/Number/MIN_VALUE"
  "built-ins/Number/prototype/toExponential"
  "built-ins/Number/prototype/toFixed"
  "built-ins/Number/prototype/toString"
  "built-ins/Number/prototype/valueOf"
  "built-ins/Object/defineProperties"
  "built-ins/Object/freeze"
  "built-ins/Object/fromEntries"
  "built-ins/Object/getOwnPropertyDescriptor"
  "built-ins/Object/getOwnPropertyNames"
  "built-ins/Object/getPrototypeOf"
  "built-ins/Object/hasOwn"
  "built-ins/Object/isExtensible"
  "built-ins/Object/preventExtensions"
  "built-ins/Object/seal"
  "built-ins/Object/setPrototypeOf"
  "built-ins/String/prototype"
  "built-ins/String/prototype/at"
  "built-ins/String/prototype/charAt"
  "built-ins/String/prototype/charCodeAt"
  "built-ins/String/prototype/codePointAt"
  "built-ins/String/prototype/concat"
  "built-ins/String/prototype/endsWith"
  "built-ins/String/prototype/includes"
  "built-ins/String/prototype/indexOf"
  "built-ins/String/prototype/lastIndexOf"
  "built-ins/String/prototype/slice"
  "built-ins/String/prototype/split"
  "built-ins/String/prototype/startsWith"
  "built-ins/String/prototype/substring"
  "built-ins/Math/ceil"
  "built-ins/Math/round"
  "built-ins/Math/sqrt"
  "built-ins/Math/trunc"
  "built-ins/Math/sign"
  "built-ins/Math/pow"
  "built-ins/decodeURIComponent"
  "built-ins/encodeURIComponent"
  "built-ins/Symbol/prototype"
  "built-ins/Error/isError"
  "built-ins/Function/prototype/apply"
  "built-ins/Function/prototype/bind"
  "built-ins/Function/prototype/call"
  "built-ins/Date"
  "built-ins/Date/now"
  "built-ins/Date/parse"
  "built-ins/Date/prototype"
  "built-ins/RegExp"
  "built-ins/RegExp/prototype"
  "built-ins/RegExp/prototype/exec"
  "built-ins/RegExp/prototype/test"
  "built-ins/Promise"
  "built-ins/Promise/all"
  "built-ins/Promise/prototype"
  "built-ins/Promise/prototype/then"
  "built-ins/Promise/resolve"
  "built-ins/Map"
  "built-ins/Map/prototype"
  "built-ins/Map/prototype/get"
  "built-ins/Map/prototype/set"
  "built-ins/Set"
  "built-ins/Set/prototype"
  "built-ins/Set/prototype/add"
  "built-ins/Set/prototype/has"
  "built-ins/WeakMap/prototype"
  "built-ins/WeakSet/prototype"
  "built-ins/Proxy/get"
  "built-ins/Proxy/set"
  "built-ins/Reflect/get"
  "built-ins/Reflect/set"
  "built-ins/Reflect/apply"
  "built-ins/Iterator/from"
  "built-ins/Iterator/prototype"
  "built-ins/GeneratorFunction"
  "built-ins/GeneratorFunction/prototype"
  "built-ins/AsyncFunction"
  "built-ins/JSON/isRawJSON"
  "built-ins/Object/prototype"
  "built-ins/Object/prototype/hasOwnProperty"
  "built-ins/Object/prototype/toString"
  "built-ins/NativeErrors/RangeError"
  "built-ins/NativeErrors/RangeError/prototype"
  "built-ins/NativeErrors/TypeError"
  "built-ins/NativeErrors/TypeError/prototype"
  "built-ins/Array/fromAsync"
  "built-ins/DataView/prototype"
  "built-ins/Atomics/load"
  "built-ins/Atomics/store"
  "built-ins/TypedArray/prototype"
  "built-ins/StringIteratorPrototype"
  "built-ins/MapIteratorPrototype"
  "built-ins/SetIteratorPrototype"
  "built-ins/RegExpStringIteratorPrototype"
  "built-ins/Function/prototype/constructor"
  "built-ins/Function/prototype/toString"
  "built-ins/Error/prototype/constructor"
  "built-ins/Error/prototype/toString"
  "built-ins/Symbol/match"
  "built-ins/Symbol/replace"
  "built-ins/Symbol/search"
  "built-ins/Symbol/split"
  "built-ins/Symbol/toPrimitive"
  "built-ins/Number/POSITIVE_INFINITY"
  "built-ins/Number/NEGATIVE_INFINITY"
  "built-ins/Math/exp"
  "built-ins/Math/log"
  "built-ins/Math/sin"
  "built-ins/Math/cos"
  "built-ins/Math/tan"
  "built-ins/Date/prototype/getTime"
  "built-ins/Date/prototype/toString"
  "built-ins/Date/UTC"
  "built-ins/Promise/prototype/catch"
  "built-ins/Promise/reject"
  "built-ins/Map/prototype/has"
  "built-ins/Map/prototype/delete"
  "built-ins/Set/prototype/delete"
  "built-ins/Proxy/has"
  "built-ins/Reflect/has"
  "built-ins/Reflect/construct"
)

for p in "${patterns[@]}"; do
  node -e "
  const fs=require('fs');
  const cfg=JSON.parse(fs.readFileSync('$CONFIG','utf8'));
  cfg.patterns=['$p'];
  fs.writeFileSync('$CONFIG', JSON.stringify(cfg, null, 2));
  "
  out=$(node "$RUNNER" 2>&1) || true
  snap=$(echo "$out" | grep -o 'tests/test262/reports/snapshot-[^ ]*\.json' | tail -1)
  if [ -z "$snap" ] || [ ! -f "$REPO/$snap" ]; then echo "No snapshot for $p"; exit 1; fi
  read -r total passed fs fm to <<< $(node -e "const s=require('./$snap'); console.log(s.total, s.summary.passed, s.summary.failed_syntax, s.summary.failed_semantics, s.summary.timeout)")
  node "$ADD_ROW" "$p" "$total" "$passed" "$fs" "$fm" "$to"
  git add CONFORMANCE_JS.md "$CONFIG" "$snap"
  git commit -m "docs(test262): record $p conformance"
  echo "Done: $p ($total tests)"
done
echo "All 100 batches done."
