#!/usr/bin/env bash
# Run 100 more Test262 batches (continuation after GeneratorFunction/prototype). Doc + commit each.
set -e
REPO=/home/gamarino/Documentos/proyectos/protoJS
CONFIG="$REPO/tests/test262/config/test262_paths.json"
RUNNER="$REPO/tests/test262/runner/test262_runner.js"
ADD_ROW="$REPO/tests/test262/runner/add_conformance_row.js"
export PROTOJS=$REPO/build/protojs
export TEST262_ROOT=/home/gamarino/Documentos/proyectos/test262
cd "$REPO"

patterns=(
  "built-ins/AsyncFunction"
  "built-ins/JSON/isRawJSON"
  "built-ins/JSON/rawJSON"
  "built-ins/Object/prototype"
  "built-ins/Object/prototype/hasOwnProperty"
  "built-ins/Object/prototype/toString"
  "built-ins/NativeErrors/RangeError"
  "built-ins/NativeErrors/RangeError/prototype"
  "built-ins/NativeErrors/TypeError"
  "built-ins/NativeErrors/TypeError/prototype"
  "built-ins/Array/fromAsync"
  "built-ins/DataView/prototype"
  "built-ins/Atomics/load"
  "built-ins/Atomics/store"
  "built-ins/TypedArray/prototype"
  "built-ins/StringIteratorPrototype"
  "built-ins/MapIteratorPrototype"
  "built-ins/SetIteratorPrototype"
  "built-ins/RegExpStringIteratorPrototype"
  "built-ins/Function/prototype/constructor"
  "built-ins/Function/prototype/toString"
  "built-ins/Error/prototype/constructor"
  "built-ins/Error/prototype/toString"
  "built-ins/Symbol/match"
  "built-ins/Symbol/replace"
  "built-ins/Symbol/search"
  "built-ins/Symbol/split"
  "built-ins/Symbol/toPrimitive"
  "built-ins/Number/POSITIVE_INFINITY"
  "built-ins/Number/NEGATIVE_INFINITY"
  "built-ins/Math/exp"
  "built-ins/Math/log"
  "built-ins/Math/sin"
  "built-ins/Math/cos"
  "built-ins/Math/tan"
  "built-ins/Date/prototype/getTime"
  "built-ins/Date/prototype/toString"
  "built-ins/Date/UTC"
  "built-ins/Promise/prototype/catch"
  "built-ins/Promise/reject"
  "built-ins/Map/prototype/has"
  "built-ins/Map/prototype/delete"
  "built-ins/Set/prototype/delete"
  "built-ins/Proxy/has"
  "built-ins/Reflect/has"
  "built-ins/Reflect/construct"
  "built-ins/Iterator/concat"
  "built-ins/Iterator/zip"
  "built-ins/AsyncGeneratorFunction"
  "built-ins/AsyncGeneratorFunction/prototype"
  "built-ins/GeneratorPrototype"
  "built-ins/GeneratorPrototype/next"
  "built-ins/RegExp/prototype/Symbol.match"
  "built-ins/RegExp/prototype/Symbol.replace"
  "built-ins/RegExp/prototype/Symbol.search"
  "built-ins/RegExp/prototype/Symbol.split"
  "built-ins/String/prototype/match"
  "built-ins/String/prototype/replace"
  "built-ins/String/prototype/repeat"
  "built-ins/String/prototype/trim"
  "built-ins/ArrayBuffer/prototype/detached"
  "built-ins/ArrayBuffer/prototype/resize"
  "built-ins/ArrayBuffer/prototype/transfer"
  "built-ins/BigInt/parseInt"
  "built-ins/BigInt/prototype/toString"
  "built-ins/Object/getOwnPropertySymbols"
  "built-ins/Object/getOwnPropertyDescriptors"
  "built-ins/Reflect/defineProperty"
  "built-ins/Reflect/deleteProperty"
  "built-ins/Reflect/getOwnPropertyDescriptor"
  "built-ins/Reflect/getPrototypeOf"
  "built-ins/Proxy/construct"
  "built-ins/Proxy/defineProperty"
  "built-ins/Proxy/getOwnPropertyDescriptor"
  "built-ins/Map/prototype/entries"
  "built-ins/Map/prototype/forEach"
  "built-ins/Map/prototype/keys"
  "built-ins/Map/prototype/values"
  "built-ins/Set/prototype/entries"
  "built-ins/Set/prototype/forEach"
  "built-ins/Set/prototype/values"
  "built-ins/Promise/allSettled"
  "built-ins/Promise/any"
  "built-ins/Promise/race"
  "built-ins/RegExp/escape"
  "built-ins/String/prototype/padStart"
  "built-ins/String/prototype/padEnd"
  "built-ins/String/prototype/normalize"
  "built-ins/String/prototype/matchAll"
  "built-ins/String/prototype/search"
  "built-ins/Number/prototype/toPrecision"
  "built-ins/Number/prototype/toLocaleString"
  "built-ins/Math/random"
  "built-ins/Math/expm1"
  "built-ins/Math/asin"
  "built-ins/Math/acos"
  "built-ins/Math/atan"
  "built-ins/Math/atan2"
  "built-ins/Date/prototype/getFullYear"
  "built-ins/Date/prototype/getMonth"
  "built-ins/Date/prototype/getDate"
  "built-ins/Date/prototype/getHours"
  "built-ins/Date/prototype/getMinutes"
  "built-ins/Date/prototype/getSeconds"
  "built-ins/TypedArray/from"
  "built-ins/TypedArray/of"
  "built-ins/TypedArrayConstructors/Int8Array"
  "built-ins/TypedArrayConstructors/Uint8Array"
  "built-ins/TypedArrayConstructors/Int16Array"
  "built-ins/TypedArrayConstructors/Uint16Array"
  "built-ins/TypedArrayConstructors/Int32Array"
  "built-ins/TypedArrayConstructors/Uint32Array"
  "built-ins/TypedArrayConstructors/Float32Array"
  "built-ins/TypedArrayConstructors/Float64Array"
  "built-ins/WeakMap/prototype/get"
  "built-ins/WeakMap/prototype/has"
  "built-ins/WeakMap/prototype/set"
  "built-ins/WeakSet/prototype/add"
  "built-ins/WeakSet/prototype/has"
  "built-ins/WeakSet/prototype/delete"
  "built-ins/Promise/prototype/finally"
  "built-ins/Iterator/prototype/map"
  "built-ins/Iterator/prototype/filter"
  "built-ins/Iterator/prototype/take"
  "built-ins/Iterator/prototype/toArray"
  "built-ins/AsyncIteratorPrototype"
  "built-ins/AsyncGeneratorPrototype"
  "built-ins/AsyncGeneratorPrototype/next"
  "built-ins/NativeErrors/EvalError"
  "built-ins/NativeErrors/ReferenceError"
  "built-ins/NativeErrors/SyntaxError"
)

for p in "${patterns[@]}"; do
  node -e "
  const fs=require('fs');
  const cfg=JSON.parse(fs.readFileSync('$CONFIG','utf8'));
  cfg.patterns=['$p'];
  fs.writeFileSync('$CONFIG', JSON.stringify(cfg, null, 2));
  "
  out=$(node "$RUNNER" 2>&1) || true
  snap=$(echo "$out" | grep -o 'tests/test262/reports/snapshot-[^ ]*\.json' | tail -1)
  if [ -z "$snap" ] || [ ! -f "$REPO/$snap" ]; then echo "No snapshot for $p"; exit 1; fi
  read -r total passed fs fm to <<< $(node -e "const s=require('./$snap'); console.log(s.total, s.summary.passed, s.summary.failed_syntax, s.summary.failed_semantics, s.summary.timeout)")
  node "$ADD_ROW" "$p" "$total" "$passed" "$fs" "$fm" "$to"
  git add CONFORMANCE_JS.md "$CONFIG" "$snap"
  git commit -m "docs(test262): record $p conformance"
  echo "Done: $p ($total tests)"
done
echo "All 100 batches done."
