#include "JSSymbols.h"
#include <mutex>
#include <string>
#include <array>
#include <unordered_map>

namespace protojs::JSSymbols {

// Helper macro: define a lazy getter that interns "literal" on first call.
// NOLINTNEXTLINE(cppcoreguidelines-macro-usage)
#define DEFINE_SYMBOL(getter, literal)                                      \
    const proto::ProtoString* getter(proto::ProtoContext* ctx) {            \
        static const proto::ProtoString* s_sym = nullptr;                   \
        static std::once_flag s_flag;                                        \
        /* Any valid ctx suffices: createSymbol interns at ProtoSpace level, \
         * so the result is globally unique regardless of which ctx wins.  */ \
        std::call_once(s_flag, [ctx]() {                                    \
            s_sym = proto::ProtoString::createSymbol(ctx, literal);         \
        });                                                                  \
        return s_sym;                                                        \
    }

// ---- JS global constructor names ----------------------------------------
DEFINE_SYMBOL(Array,       "Array")
DEFINE_SYMBOL(Function,    "Function")
DEFINE_SYMBOL(Math,        "Math")
DEFINE_SYMBOL(Number,      "Number")
DEFINE_SYMBOL(Object,      "Object")
DEFINE_SYMBOL(RegExp,      "RegExp")
DEFINE_SYMBOL(String,      "String")

// ---- Common JS property names -------------------------------------------
DEFINE_SYMBOL(apply,            "apply")
DEFINE_SYMBOL(bind,             "bind")
DEFINE_SYMBOL(call,             "call")
DEFINE_SYMBOL(constructor,      "constructor")
DEFINE_SYMBOL(createdTimestamp, "createdTimestamp")
DEFINE_SYMBOL(description,      "description")
DEFINE_SYMBOL(done,             "done")
DEFINE_SYMBOL(dotAll,           "dotAll")
DEFINE_SYMBOL(elements,         "elements")
DEFINE_SYMBOL(exports,          "exports")
DEFINE_SYMBOL(flags,            "flags")
DEFINE_SYMBOL(global,           "global")
DEFINE_SYMBOL(ignoreCase,       "ignoreCase")
DEFINE_SYMBOL(index,            "index")
DEFINE_SYMBOL(input,            "input")
DEFINE_SYMBOL(isRoot,           "isRoot")
DEFINE_SYMBOL(isWeakRef,        "isWeakRef")
DEFINE_SYMBOL(jsValueTag,       "jsValueTag")
DEFINE_SYMBOL(lastIndex,        "lastIndex")
DEFINE_SYMBOL(length,           "length")
DEFINE_SYMBOL(message,          "message")
DEFINE_SYMBOL(multiline,        "multiline")
DEFINE_SYMBOL(name,             "name")
DEFINE_SYMBOL(next,             "next")
DEFINE_SYMBOL(prototype,        "prototype")
DEFINE_SYMBOL(protoObj,         "protoObj")
DEFINE_SYMBOL(require,          "require")
DEFINE_SYMBOL(stringProtoBuild, "__string_proto_built__")
DEFINE_SYMBOL(source,           "source")
DEFINE_SYMBOL(sticky,           "sticky")
DEFINE_SYMBOL(toExponential,    "toExponential")
DEFINE_SYMBOL(toFixed,          "toFixed")
DEFINE_SYMBOL(toPrecision,      "toPrecision")
DEFINE_SYMBOL(toString,         "toString")
DEFINE_SYMBOL(unicode,          "unicode")
DEFINE_SYMBOL(value,            "value")
DEFINE_SYMBOL(valueOf,          "valueOf")
DEFINE_SYMBOL(values,           "values")
DEFINE_SYMBOL(groups,           "groups")
DEFINE_SYMBOL(hasIndices,       "hasIndices")
DEFINE_SYMBOL(indices,          "indices")

// ---- Internal implementation keys ---------------------------------------
DEFINE_SYMBOL(arrayCtor,        "__array_ctor__")
DEFINE_SYMBOL(arrayProto,       "__array_proto__")
DEFINE_SYMBOL(boundArgs,        "__bound_args__")
DEFINE_SYMBOL(boundFn,          "__bound_fn__")
DEFINE_SYMBOL(boundThis,        "__bound_this__")
DEFINE_SYMBOL(bytecodeId,       "__bytecode_id__")
DEFINE_SYMBOL(errorCtor,        "__error_ctor__")
DEFINE_SYMBOL(externalPtrField, "_externalPtr")
DEFINE_SYMBOL(functionProto,    "__function_proto__")
DEFINE_SYMBOL(iterArr,          "__iter_arr__")
DEFINE_SYMBOL(iterIdx,          "__iter_idx__")
DEFINE_SYMBOL(iterKind,         "__iter_kind__")
DEFINE_SYMBOL(iterSlot,         "__iter_slot__")
DEFINE_SYMBOL(jsValuePtrField,  "_jsValuePtr")
DEFINE_SYMBOL(jsValueTagField,  "_jsValueTag")
DEFINE_SYMBOL(reBytecode,       "__re_bytecode__")
DEFINE_SYMBOL(regexpCtor,       "__regexp_ctor__")
DEFINE_SYMBOL(iterDone,         "__iter_done__")
DEFINE_SYMBOL(iterRe,           "__iter_re__")
DEFINE_SYMBOL(iterStr,          "__iter_str__")
DEFINE_SYMBOL(isArray,          "__is_array__")
DEFINE_SYMBOL(stringCtor,       "__string_ctor__")
DEFINE_SYMBOL(primitiveValue,   "__primitive_value__")
DEFINE_SYMBOL(arrowThis,        "__arrow_this__")

// ---- TypedArray / ArrayBuffer / DataView internal keys ------------------
DEFINE_SYMBOL(abData,        "__ab_data__")
DEFINE_SYMBOL(abDetached,    "__ab_detached__")
DEFINE_SYMBOL(taBuffer,      "__ta_buffer__")
DEFINE_SYMBOL(taElementType, "__ta_element_type__")
DEFINE_SYMBOL(taByteOffset,  "__ta_byte_offset__")
DEFINE_SYMBOL(taCtor,        "__typed_array_ctor__")
DEFINE_SYMBOL(dvBuffer,      "__dv_buffer__")
DEFINE_SYMBOL(dvByteOffset,  "__dv_byte_offset__")
DEFINE_SYMBOL(dvByteLength,  "__dv_byte_length__")

// ---- TypedArray / ArrayBuffer / DataView JS property names -------------
DEFINE_SYMBOL(ArrayBuffer,         "ArrayBuffer")
DEFINE_SYMBOL(DataView,            "DataView")
DEFINE_SYMBOL(Int8Array,           "Int8Array")
DEFINE_SYMBOL(Uint8Array,          "Uint8Array")
DEFINE_SYMBOL(Uint8ClampedArray,   "Uint8ClampedArray")
DEFINE_SYMBOL(Int16Array,          "Int16Array")
DEFINE_SYMBOL(Uint16Array,         "Uint16Array")
DEFINE_SYMBOL(Int32Array,          "Int32Array")
DEFINE_SYMBOL(Uint32Array,         "Uint32Array")
DEFINE_SYMBOL(Float32Array,        "Float32Array")
DEFINE_SYMBOL(Float64Array,        "Float64Array")
DEFINE_SYMBOL(BigInt64Array,       "BigInt64Array")
DEFINE_SYMBOL(BigUint64Array,      "BigUint64Array")
DEFINE_SYMBOL(byteLength,          "byteLength")
DEFINE_SYMBOL(byteOffset,          "byteOffset")
DEFINE_SYMBOL(buffer,              "buffer")
DEFINE_SYMBOL(BYTES_PER_ELEMENT,   "BYTES_PER_ELEMENT")
DEFINE_SYMBOL(slice,               "slice")
DEFINE_SYMBOL(isView,              "isView")
DEFINE_SYMBOL(fill,                "fill")
DEFINE_SYMBOL(forEach,             "forEach")
DEFINE_SYMBOL(map,                 "map")
DEFINE_SYMBOL(filter,              "filter")
DEFINE_SYMBOL(indexOf,             "indexOf")
DEFINE_SYMBOL(lastIndexOf,         "lastIndexOf")
DEFINE_SYMBOL(includes,            "includes")
DEFINE_SYMBOL(find,                "find")
DEFINE_SYMBOL(findIndex,           "findIndex")
DEFINE_SYMBOL(every,               "every")
DEFINE_SYMBOL(some,                "some")
DEFINE_SYMBOL(join,                "join")
DEFINE_SYMBOL(reverse,             "reverse")
DEFINE_SYMBOL(sort,                "sort")
DEFINE_SYMBOL(copyWithin,          "copyWithin")
DEFINE_SYMBOL(subarray,            "subarray")
DEFINE_SYMBOL(at,                  "at")
DEFINE_SYMBOL(set,                 "set")
DEFINE_SYMBOL(reduce,              "reduce")
DEFINE_SYMBOL(reduceRight,         "reduceRight")
DEFINE_SYMBOL(from,                "from")
DEFINE_SYMBOL(of,                  "of")
DEFINE_SYMBOL(keys,                "keys")
DEFINE_SYMBOL(entries,             "entries")
DEFINE_SYMBOL(getInt8,             "getInt8")
DEFINE_SYMBOL(getUint8,            "getUint8")
DEFINE_SYMBOL(getInt16,            "getInt16")
DEFINE_SYMBOL(getUint16,           "getUint16")
DEFINE_SYMBOL(getInt32,            "getInt32")
DEFINE_SYMBOL(getUint32,           "getUint32")
DEFINE_SYMBOL(getFloat32,          "getFloat32")
DEFINE_SYMBOL(getFloat64,          "getFloat64")
DEFINE_SYMBOL(getBigInt64,         "getBigInt64")
DEFINE_SYMBOL(getBigUint64,        "getBigUint64")
DEFINE_SYMBOL(setInt8,             "setInt8")
DEFINE_SYMBOL(setUint8,            "setUint8")
DEFINE_SYMBOL(setInt16,            "setInt16")
DEFINE_SYMBOL(setUint16,           "setUint16")
DEFINE_SYMBOL(setInt32,            "setInt32")
DEFINE_SYMBOL(setUint32,           "setUint32")
DEFINE_SYMBOL(setFloat32,          "setFloat32")
DEFINE_SYMBOL(setFloat64,          "setFloat64")
DEFINE_SYMBOL(setBigInt64,         "setBigInt64")
DEFINE_SYMBOL(setBigUint64,        "setBigUint64")

// ---- Well-known JS protocol symbols -------------------------------------
DEFINE_SYMBOL(symbolMatch,   "Symbol.match")
DEFINE_SYMBOL(symbolReplace, "Symbol.replace")
DEFINE_SYMBOL(symbolSearch,  "Symbol.search")
DEFINE_SYMBOL(symbolSplit,   "Symbol.split")
DEFINE_SYMBOL(symbolMatchAll,   "Symbol.matchAll")
DEFINE_SYMBOL(symbolIterator,    "Symbol.iterator")

#undef DEFINE_SYMBOL

// ---- Numeric index symbols ----------------------------------------------
namespace {
    constexpr uint32_t kIndexCacheSize = 256;
    std::array<const proto::ProtoString*, kIndexCacheSize> s_indexCache{};
    std::array<std::once_flag, kIndexCacheSize> s_indexFlags{};
}

const proto::ProtoString* indexKey(proto::ProtoContext* ctx, uint32_t i) {
    if (i < kIndexCacheSize) {
        std::call_once(s_indexFlags[i], [ctx, i]() {
            s_indexCache[i] = proto::ProtoString::createSymbol(ctx, std::to_string(i).c_str());
        });
        return s_indexCache[i];
    }
    return proto::ProtoString::createSymbol(ctx, std::to_string(i).c_str());
}

std::string getNameFromHash(proto::ProtoContext* ctx, unsigned long hash) {
    // Build a static hash→name map once, covering all known JSSymbols keys.
    // Any ctx suffices — createSymbol interns at ProtoSpace level.
    static std::unordered_map<unsigned long, std::string> s_map;
    static std::once_flag s_mapFlag;
    std::call_once(s_mapFlag, [ctx]() {
#define REGISTER(getter, literal) \
        s_map[getter(ctx)->getHash(ctx)] = literal;
        REGISTER(Array,           "Array")
        REGISTER(Function,        "Function")
        REGISTER(Math,            "Math")
        REGISTER(Number,          "Number")
        REGISTER(Object,          "Object")
        REGISTER(RegExp,          "RegExp")
        REGISTER(String,          "String")
        REGISTER(constructor,     "constructor")
        REGISTER(createdTimestamp,"createdTimestamp")
        REGISTER(description,     "description")
        REGISTER(done,            "done")
        REGISTER(dotAll,          "dotAll")
        REGISTER(elements,        "elements")
        REGISTER(exports,         "exports")
        REGISTER(flags,           "flags")
        REGISTER(global,          "global")
        REGISTER(ignoreCase,      "ignoreCase")
        REGISTER(index,           "index")
        REGISTER(input,           "input")
        REGISTER(isRoot,          "isRoot")
        REGISTER(isWeakRef,       "isWeakRef")
        REGISTER(jsValueTag,      "jsValueTag")
        REGISTER(lastIndex,       "lastIndex")
        REGISTER(length,          "length")
        REGISTER(message,         "message")
        REGISTER(multiline,       "multiline")
        REGISTER(name,            "name")
        REGISTER(next,            "next")
        REGISTER(prototype,       "prototype")
        REGISTER(protoObj,        "protoObj")
        REGISTER(require,         "require")
        REGISTER(source,          "source")
        REGISTER(sticky,          "sticky")
        REGISTER(toExponential,   "toExponential")
        REGISTER(toFixed,         "toFixed")
        REGISTER(toPrecision,     "toPrecision")
        REGISTER(toString,        "toString")
        REGISTER(unicode,         "unicode")
        REGISTER(value,           "value")
        REGISTER(valueOf,         "valueOf")
        REGISTER(values,          "values")
        REGISTER(apply,           "apply")
        REGISTER(bind,            "bind")
        REGISTER(call,            "call")
        REGISTER(arrayCtor,       "__array_ctor__")
        REGISTER(arrayProto,      "__array_proto__")
        REGISTER(boundArgs,       "__bound_args__")
        REGISTER(boundFn,         "__bound_fn__")
        REGISTER(boundThis,       "__bound_this__")
        REGISTER(bytecodeId,      "__bytecode_id__")
        REGISTER(errorCtor,       "__error_ctor__")
        REGISTER(externalPtrField,"_externalPtr")
        REGISTER(functionProto,   "__function_proto__")
        REGISTER(iterArr,         "__iter_arr__")
        REGISTER(iterIdx,         "__iter_idx__")
        REGISTER(iterKind,        "__iter_kind__")
        REGISTER(iterSlot,        "__iter_slot__")
        REGISTER(jsValuePtrField, "_jsValuePtr")
        REGISTER(jsValueTagField, "_jsValueTag")
        REGISTER(reBytecode,      "__re_bytecode__")
        REGISTER(regexpCtor,      "__regexp_ctor__")
        REGISTER(symbolMatch,     "Symbol.match")
        REGISTER(symbolReplace,   "Symbol.replace")
        REGISTER(symbolSearch,    "Symbol.search")
        REGISTER(symbolSplit,     "Symbol.split")
        REGISTER(symbolMatchAll,  "Symbol.matchAll")
        REGISTER(symbolIterator,  "Symbol.iterator")
        REGISTER(groups,          "groups")
        REGISTER(hasIndices,      "hasIndices")
        REGISTER(indices,         "indices")
        REGISTER(iterDone,      "__iter_done__")
        REGISTER(iterRe,        "__iter_re__")
        REGISTER(iterStr,       "__iter_str__")
        REGISTER(isArray,       "__is_array__")
        REGISTER(stringCtor,    "__string_ctor__")
        REGISTER(primitiveValue,"__primitive_value__")
        REGISTER(abData,        "__ab_data__")
        REGISTER(abDetached,    "__ab_detached__")
        REGISTER(taBuffer,      "__ta_buffer__")
        REGISTER(taElementType, "__ta_element_type__")
        REGISTER(taByteOffset,  "__ta_byte_offset__")
        REGISTER(taCtor,        "__typed_array_ctor__")
        REGISTER(dvBuffer,      "__dv_buffer__")
        REGISTER(dvByteOffset,  "__dv_byte_offset__")
        REGISTER(dvByteLength,  "__dv_byte_length__")
        REGISTER(ArrayBuffer,         "ArrayBuffer")
        REGISTER(DataView,            "DataView")
        REGISTER(Int8Array,           "Int8Array")
        REGISTER(Uint8Array,          "Uint8Array")
        REGISTER(Uint8ClampedArray,   "Uint8ClampedArray")
        REGISTER(Int16Array,          "Int16Array")
        REGISTER(Uint16Array,         "Uint16Array")
        REGISTER(Int32Array,          "Int32Array")
        REGISTER(Uint32Array,         "Uint32Array")
        REGISTER(Float32Array,        "Float32Array")
        REGISTER(Float64Array,        "Float64Array")
        REGISTER(BigInt64Array,       "BigInt64Array")
        REGISTER(BigUint64Array,      "BigUint64Array")
        REGISTER(byteLength,          "byteLength")
        REGISTER(byteOffset,          "byteOffset")
        REGISTER(buffer,              "buffer")
        REGISTER(BYTES_PER_ELEMENT,   "BYTES_PER_ELEMENT")
        REGISTER(slice,               "slice")
        REGISTER(isView,              "isView")
        REGISTER(fill,                "fill")
        REGISTER(forEach,             "forEach")
        REGISTER(map,                 "map")
        REGISTER(filter,              "filter")
        REGISTER(indexOf,             "indexOf")
        REGISTER(lastIndexOf,         "lastIndexOf")
        REGISTER(includes,            "includes")
        REGISTER(find,                "find")
        REGISTER(findIndex,           "findIndex")
        REGISTER(every,               "every")
        REGISTER(some,                "some")
        REGISTER(join,                "join")
        REGISTER(reverse,             "reverse")
        REGISTER(sort,                "sort")
        REGISTER(copyWithin,          "copyWithin")
        REGISTER(subarray,            "subarray")
        REGISTER(at,                  "at")
        REGISTER(set,                 "set")
        REGISTER(reduce,              "reduce")
        REGISTER(reduceRight,         "reduceRight")
        REGISTER(from,                "from")
        REGISTER(of,                  "of")
        REGISTER(keys,                "keys")
        REGISTER(entries,             "entries")
        REGISTER(getInt8,             "getInt8")
        REGISTER(getUint8,            "getUint8")
        REGISTER(getInt16,            "getInt16")
        REGISTER(getUint16,           "getUint16")
        REGISTER(getInt32,            "getInt32")
        REGISTER(getUint32,           "getUint32")
        REGISTER(getFloat32,          "getFloat32")
        REGISTER(getFloat64,          "getFloat64")
        REGISTER(getBigInt64,         "getBigInt64")
        REGISTER(getBigUint64,        "getBigUint64")
        REGISTER(setInt8,             "setInt8")
        REGISTER(setUint8,            "setUint8")
        REGISTER(setInt16,            "setInt16")
        REGISTER(setUint16,           "setUint16")
        REGISTER(setInt32,            "setInt32")
        REGISTER(setUint32,           "setUint32")
        REGISTER(setFloat32,          "setFloat32")
        REGISTER(setFloat64,          "setFloat64")
        REGISTER(setBigInt64,         "setBigInt64")
        REGISTER(setBigUint64,        "setBigUint64")
#undef REGISTER
    });
    auto it = s_map.find(hash);
    return it != s_map.end() ? it->second : std::string{};
}

} // namespace protojs::JSSymbols
